### ISSUE TITLE
Is this the official implementation?

### ISSUE THREAD

**Issue by superYuezhang** [harshakmohan/NeuSDFusion#1]
I am very interested in this paper and I would like to ask is this the official code?

**Comment by harshakmohan** [comment]
> I am very interested in this paper and I would like to ask is this the official code?

It's not official code. They haven't released official code for this paper.

**Comment by superYuezhang** [comment]
Thank you for your reply!

发件人: Harsha Mohan ***@***.***>
日期: 星期五, 2024年11月29日 11:17
收件人: harshakmohan/NeuSDFusion ***@***.***>
抄送: Yue Zhang (张越) ***@***.***>, Author ***@***.***>
主题: Re: [harshakmohan/NeuSDFusion] Is this the official implementation? (Issue #1)

I am very interested in this paper and I would like to ask is this the official code?

It's not official code. They haven't released official code for this paper.

―

**Comment by superYuezhang** [comment]
> > I am very interested in this paper and I would like to ask is this the official code?
> 
> It's not official code. They haven't released official code for this paper.

Thank you for your reply!
